trigger: none

variables:
- group: SKEDDA-DOTNET

stages:
- stage: TF_DESTROY
  pool:
    vmImage: ubuntu-latest
  condition: always()
  jobs:
    - job: Infrastructure_Terraform_Destroy
      displayName: "Infrastructure Terraform Destroy"
      steps:
        - script: |
            cd $(Build.Repository.LocalPath)/infrastructure
            pwd
            wget --quiet "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
            unzip "terraform_${TF_VERSION}_linux_amd64.zip"
            rm "terraform_${TF_VERSION}_linux_amd64.zip"
          displayName: Install Terraform

        - script: |
            export TF_IN_AUTOMATION=true
            cd $(Build.Repository.LocalPath)/infrastructure
            ./terraform validate
            ./terraform init
          displayName: Terraform Initialize
          env:
            ARM_TENANT_ID: $(tenant_id)
            ARM_SUBSCRIPTION_ID: $(subscription_id)
            ARM_CLIENT_ID: $(client_id)
            ARM_CLIENT_SECRET: $(client_secret)
            ARM_ACCESS_KEY: $(backend_access_key)
            ARM_SKIP_PROVIDER_REGISTRATION: $(tf_provider_registration)
            AZDO_PERSONAL_ACCESS_TOKEN: $(pat_token)
            TF_VAR_sql_admin_username: $(sql_admin_username)
            TF_VAR_sql_admin_password: $(sql_admin_password)
            TF_VAR_connection_string_value: $(db_connection_string)      

        - script: |
            export TF_IN_AUTOMATION=true
            cd $(Build.Repository.LocalPath)/infrastructure
            ./terraform validate
            ./terraform init
            ./terraform destroy -auto-approve \
            -var-file="terraform.tfvars"
          displayName: Terraform Destroy
          env:
            ARM_TENANT_ID: $(tenant_id)
            ARM_SUBSCRIPTION_ID: $(subscription_id)
            ARM_CLIENT_ID: $(client_id)
            ARM_CLIENT_SECRET: $(client_secret)
            ARM_ACCESS_KEY: $(backend_access_key)
            ARM_SKIP_PROVIDER_REGISTRATION: $(tf_provider_registration)
            AZDO_PERSONAL_ACCESS_TOKEN: $(pat_token)
            TF_VAR_sql_admin_username: $(sql_admin_username)
            TF_VAR_sql_admin_password: $(sql_admin_password)
            TF_VAR_connection_string_value: $(db_connection_string)  